name: homelab

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  homelab:
    external: true
    name: homelab

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  dnsmasq_data:
    external: true
  pihole_data:
    external: true
  portainer_data:
    external: true

# =============================================================================
# SERVICES
# =============================================================================
services:

  # ---------------------------------------------------------------------------
  # HOMELAB UTILITIES
  # ---------------------------------------------------------------------------

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    command: ["node", "server.js"]
    entrypoint: ["docker-entrypoint.sh"]
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "${HOST_IP}:3000,brickserver:3000"
      NODE_ENV: production
      PORT: "3000"
      HOMEPAGE_VAR_PIHOLE_API_KEY: ${PIHOLE_API_KEY}
      HOMEPAGE_VAR_TAILSCALE_DEVICE_ID: ${TAILSCALE_DEVICE_ID}
      HOMEPAGE_VAR_TAILSCALE_API_KEY: ${TAILSCALE_API_KEY}
      HOMEPAGE_VAR_PORTAINER_API_KEY: ${PORTAINER_API_KEY}
      HOMEPAGE_VAR_HOST_IP: ${HOST_IP}
      HOMEPAGE_VAR_CADDY_DOMAIN: ${CADDY_DOMAIN}
      HOMEPAGE_VAR_PLEX_TOKEN: ${PLEX_TOKEN}
    networks:
      - homelab
    ports:
      - "${HOST_IP}:3000:3000/tcp"
    user: root
    volumes:
      - /home/justin/repos/homelab/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    entrypoint: ["/portainer"]
    networks:
      - homelab
    ports:
      - "${HOST_IP}:9443:9443/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    working_dir: /

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    entrypoint: ["start.sh"]
    environment:
      TZ: America/New_York
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    networks:
      - homelab
    ports:
      - "${HOST_IP}:53:53/tcp"
      - "${HOST_IP}:53:53/udp"
      - "${HOST_IP}:8082:80/tcp"
    volumes:
      - dnsmasq_data:/etc/dnsmasq.d
      - pihole_data:/etc/pihole
    working_dir: /

  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    entrypoint: ["/usr/sbin/run.sh"]
    networks:
      - homelab
    ports:
      - "${HOST_IP}:19999:19999/tcp"
    security_opt:
      - apparmor=unconfined

  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    entrypoint: ["/init"]
    environment:
      PUID: "1000"
      PGID: "1000"
      APP_KEY: ${SPEEDTEST_APP_KEY}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: "0 */4 * * *"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - homelab
    ports:
      - "${HOST_IP}:8443:443/tcp"
      - "${HOST_IP}:8080:80/tcp"
    volumes:
      - /opt/speedtest-tracker/config:/config
    working_dir: /
