- Network Services:
    - Pihole:
        icon: mdi-pi-hole
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8082/admin
        description: network ad blocking
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}:8082/admin
        widget:
            type: pihole
            url: http://pihole
            version: 6
            key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
    - Tailscale:
        icon: mdi-tailwind
        href: https://tailscale.com
        description: router connection
        ping: https://tailscale.com
        widget:
            type: tailscale
            deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICE_ID}}
            key: {{HOMEPAGE_VAR_TAILSCALE_API_KEY}}
- Applications:
    - Portainer:
        icon: portainer
        href: https://{{HOMEPAGE_VAR_HOST_IP}}:9443
        description: Docker management
        ping: https://portainer:9443
        container: portainer
        widget:
          type: portainer
          url: https://portainer:9443
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
    - Bitwarden:
        icon: mdi-lock
        href: https://{{HOMEPAGE_VAR_CADDY_DOMAIN}}/#/login
        target: "_blank"
        description: password manager
        ping: http://localhost:8081
        widget:
            type: docker
            container: bitwarden-api
- Media:
    - Plex:
        icon: plex
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:32400/web
        target: "_blank"
        description: media server
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}:32400/web
        container: plex
        widget:
            type: plex
            url: http://{{HOMEPAGE_VAR_HOST_IP}}:32400
            key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
- Media Automation:
    - Prowlarr:
        icon: prowlarr
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9696
        description: indexer manager
        ping: http://prowlarr:9696
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}
    - Radarr:
        icon: radarr
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:7878
        description: movie library
        ping: http://radarr:7878
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}
    - Sonarr:
        icon: sonarr
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8989
        description: tv library
        ping: http://sonarr:8989
        container: sonarr
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
    - Bazarr:
        icon: bazarr
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:6767
        description: subtitles
        ping: http://bazarr:6767
        container: bazarr
        widget:
            type: bazarr
            url: http://bazarr:6767
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}
    - qBittorrent:
        icon: qbittorrent
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8090
        description: download client
        ping: http://qbittorrent:8090
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:8090
            username: {{HOMEPAGE_VAR_QBIT_USER}}
            password: {{HOMEPAGE_VAR_QBIT_PASS}}
    - Overseerr:
        icon: overseerr
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:5055
        description: request portal
        ping: http://overseerr:5055
        container: overseerr
        widget:
            type: overseerr
            url: http://overseerr:5055
            key: {{HOMEPAGE_VAR_OVERSEERR_KEY}}
- Information:
    - Speedtest Tracker:
        icon: mdi-speedometer
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
        description: speedtest
        ping: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
        container: speedtest
        widget:
            type: speedtest
            url: http://speedtest-tracker
    - Netdata:
        icon: netdata
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:19999
        description: System metrics
        widget:
              type: netdata
              url: http://netdata:19999
